name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行（北京时间 8 点）
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Stats SVG
        run: |
          wget -qO stats.svg "https://github-readme-stats.vercel.app/api?username=CheongSzesuen&show_icons=true&include_all_commits=true&theme=buefy&hide_border=true"

      - name: Extract Data from SVG
        id: stats
        run: |
          # 从 SVG 源码中，根据 data-testid 精准提取数据（最可靠方式）
          RANK=$(grep -oP '<text[^>]*data-testid="level-rank-icon"[^>]*>\s*\K[A-Z]' stats.svg)
          STARS=$(grep -oP '<text[^>]*data-testid="stars"[^>]*>\s*\K[0-9]+' stats.svg)
          COMMITS=$(grep -oP '<text[^>]*data-testid="commits"[^>]*>\s*\K[0-9]+' stats.svg)
          PRS=$(grep -oP '<text[^>]*data-testid="prs"[^>]*>\s*\K[0-9]+' stats.svg)
          ISSUES=$(grep -oP '<text[^>]*data-testid="issues"[^>]*>\s*\K[0-9]+' stats.svg)

          # 输出供后续步骤使用
          echo "rank=$RANK" >> $GITHUB_OUTPUT
          echo "stars=$STARS" >> $GITHUB_OUTPUT
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "prs=$PRS" >> $GITHUB_OUTPUT
          echo "issues=$ISSUES" >> $GITHUB_OUTPUT

          echo "=== Extracted Stats ==="
          echo "Rank: $RANK"
          echo "Stars: $STARS"
          echo "Commits: $COMMITS"
          echo "PRs: $PRS"
          echo "Issues: $ISSUES"

      - name: Update README.md
        run: |
          RANK="${{ steps.stats.outputs.rank }}"
          STARS="${{ steps.stats.outputs.stars }}"
          COMMITS="${{ steps.stats.outputs.commits }}"
          PRS="${{ steps.stats.outputs.prs }}"
          ISSUES="${{ steps.stats.outputs.issues }}"

          # 更新英文部分
          sed -i "s/# My GitHub Stats().*/# My GitHub Stats($RANK)/" README.md
          sed -i "s/# Total Stars Earned:.*/# Total Stars Earned: $STARS/" README.md
          sed -i "s/# Total Commits:.*/# Total Commits: $COMMITS/" README.md
          sed -i "s/# Total PRs:.*/# Total PRs: $PRS/" README.md
          sed -i "s/# Total Issues:.*/# Total Issues: $ISSUES/" README.md

          # 更新中文部分
          sed -i "s/# GitHub数据（）/# GitHub数据（$RANK）/" README.md
          sed -i "s/# 累计获得Stars：.*/# 累计获得Stars：$STARS/" README.md
          sed -i "s/# 累计Commits：.*/# 累计Commits：$COMMITS/" README.md
          sed -i "s/# 累计PRs：.*/# 累计PRs：$PRS/" README.md
          sed -i "s/# 累计Issues：.*/# 累计Issues：$ISSUES/" README.md

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-update GitHub stats in README'
          file_pattern: README.md
